version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/ai-testing-system
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
